version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - ./data:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD: wp
       MYSQL_DATABASE: wp
       MYSQL_USER: wp
       MYSQL_PASSWORD: wp

   wp:
     depends_on:
       - db
     build: .
     ports:
       - "8888:8080"
     environment:
       FOO: bar